"""add fields for user model

Revision ID: cfc21b2ff2e4
Revises: 4de301414048
Create Date: 2024-10-17 13:16:27.929554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc21b2ff2e4'
down_revision: Union[str, None] = '4de301414048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['supplier_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_supplier', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_customer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_customer')
    op.drop_column('users', 'is_supplier')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'supplier_id')
    # ### end Alembic commands ###
